### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [m0ri4ka/Course-project-y1#1]
1. In following code
https://github.com/m0ri4ka/Course-project-y1/blob/66813691180fca4a9fc6a876fa932684799cfba0/app.js#L3-L4
- Create function `random(max)` to avoid code duplication
- Use const instead of let
2. Quote mixing, plz select `"` or `'` for whoile project
3. https://github.com/m0ri4ka/Course-project-y1/blob/66813691180fca4a9fc6a876fa932684799cfba0/app.js#L13C1-L16C2
```js
const frogs = localStorage.getItem('frogs') || 0;
```
4. In this function we do not use `this`, so arrow syntax will be better: https://github.com/m0ri4ka/Course-project-y1/blob/66813691180fca4a9fc6a876fa932684799cfba0/app.js#L20
5. Call `updateFrogs();` just once

**Comment by m0ri4ka** [comment]
Fixed all issues. 
Additionally, unnecessary files were removed
